//! Responsive serial dashboard with bounded in-memory history.
use anyhow::{Context, Result};
use crossterm::{cursor, event::{self, Event, KeyCode}, execute, queue, style::{Color, Print, ResetColor, SetBackgroundColor, SetForegroundColor}, terminal::{self, Clear, ClearType, EnterAlternateScreen, LeaveAlternateScreen}};
use serde_json::Value;
use std::{collections::VecDeque, fs, io::{Read, Write}, path::PathBuf, time::{Duration, Instant}};
use ratatui::{backend::CrosstermBackend, layout::{Constraint, Direction, Layout, Rect}, style::{Color as TColor, Modifier, Style}, symbols, text::{Line, Span}, widgets::{Axis, Block, Borders, Cell, Chart, Dataset, Gauge, Paragraph, Row, Sparkline, Table, TableState}, Terminal as UiTerminal};

#[derive(Clone, Copy)] struct Palette { accent: Color, good: Color, warn: Color, bad: Color, muted: Color, bg: Color }
fn palette(name: &str) -> Palette { match name.to_ascii_lowercase().as_str() {
 "nord" => Palette { accent: Color::Cyan, good: Color::Green, warn: Color::Yellow, bad: Color::Red, muted: Color::DarkGrey, bg: Color::Rgb { r: 46, g: 52, b: 64 } },
 "dracula" => Palette { accent: Color::Magenta, good: Color::Green, warn: Color::Yellow, bad: Color::Red, muted: Color::DarkGrey, bg: Color::Rgb { r: 40, g: 42, b: 54 } },
 "solarized" => Palette { accent: Color::Cyan, good: Color::Green, warn: Color::Yellow, bad: Color::Red, muted: Color::DarkGrey, bg: Color::Rgb { r: 0, g: 43, b: 54 } },
 "monokai" => Palette { accent: Color::Yellow, good: Color::Green, warn: Color::Magenta, bad: Color::Red, muted: Color::DarkGrey, bg: Color::Rgb { r: 39, g: 40, b: 34 } },
 "high-contrast" | "high_contrast" => Palette { accent: Color::White, good: Color::Green, warn: Color::Yellow, bad: Color::Red, muted: Color::Grey, bg: Color::Black },
 "minimal" => Palette { accent: Color::White, good: Color::White, warn: Color::White, bad: Color::White, muted: Color::DarkGrey, bg: Color::Black },
 _ => Palette { accent: Color::Cyan, good: Color::Green, warn: Color::Yellow, bad: Color::Red, muted: Color::DarkGrey, bg: Color::Black },
} }
#[derive(Clone)] pub struct TuiOptions { pub theme: String, pub refresh_rate: u64, pub history_seconds: usize, pub config: Option<PathBuf> }
impl Default for TuiOptions { fn default() -> Self { Self { theme: "default".into(), refresh_rate: 4, history_seconds: 60, config: None } } }
pub fn options_from_config(mut options: TuiOptions) -> TuiOptions {
 let path = options.config.clone().or_else(|| std::env::var_os("XDG_CONFIG_HOME").map(PathBuf::from).or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config"))).map(|p| p.join("es32-top/config.toml")));
 let Some(path) = path else { return options }; let Ok(source) = fs::read_to_string(path) else { return options };
 for raw in source.lines() { let line = raw.split('#').next().unwrap_or("").trim(); let Some((key, value)) = line.split_once('=') else { continue }; let value = value.trim().trim_matches('"'); match key.trim() {
   "theme" => options.theme = value.into(), "refresh_rate" => if let Ok(v) = value.parse::<u64>() { options.refresh_rate = v.clamp(1, 30) }, "history_seconds" => if let Ok(v) = value.parse::<usize>() { options.history_seconds = v.clamp(10, 600) }, _ => {} } }; options
}
fn num(d: &Value, n: &str) -> f64 { d.get(n).and_then(Value::as_f64).or_else(|| d.get(n).and_then(Value::as_i64).map(|x| x as f64)).unwrap_or(0.0) }
fn uint(d: &Value, n: &str) -> u64 { d.get(n).and_then(Value::as_u64).or_else(|| d.get(n).and_then(Value::as_i64).map(|x| x.max(0) as u64)).unwrap_or(0) }
fn strv(d: &Value, n: &str, fallback: &str) -> String { d.get(n).and_then(Value::as_str).unwrap_or(fallback).into() }
fn bytes(n: u64) -> String { if n >= 1_048_576 { format!("{:.1} MiB", n as f64 / 1_048_576.0) } else if n >= 1024 { format!("{:.1} KiB", n as f64 / 1024.0) } else { format!("{n} B") } }
fn uptime(ms: u64) -> String { let s = ms / 1000; format!("{:02}:{:02}:{:02}", s / 3600, s / 60 % 60, s % 60) }
fn crop(s: &str, width: usize) -> String { let mut r: String = s.chars().take(width).collect(); if s.chars().count() > width && width > 1 { r.pop(); r.push('~'); }; r }
fn bar(pct: f64, width: usize) -> String { let on = (pct.clamp(0.0, 100.0) * width as f64 / 100.0).round() as usize; format!("{}{}", "#".repeat(on), "-".repeat(width.saturating_sub(on))) }
fn heap_pct(d: &Value) -> f64 { let total = uint(d, "total_heap"); if total == 0 { 0.0 } else { 100.0 * total.saturating_sub(uint(d, "heap")) as f64 / total as f64 } }
#[derive(Clone, Copy, PartialEq)] enum View { Dashboard, Cpu, Memory, Tasks, Network, Help }
impl View { fn title(self) -> &'static str { match self { Self::Dashboard => "DASHBOARD", Self::Cpu => "CPU", Self::Memory => "MEMORY", Self::Tasks => "TASKS", Self::Network => "NETWORK", Self::Help => "HELP" } } }
struct App { data: Value, cpu0: VecDeque<f64>, cpu1: VecDeque<f64>, selected: usize, view: View, paused: bool, confirm_kill: bool, notice: String, options: TuiOptions, last: Instant }
impl App { fn new(options: TuiOptions) -> Self { Self { data: Value::Null, cpu0: VecDeque::new(), cpu1: VecDeque::new(), selected: 0, view: View::Dashboard, paused: false, confirm_kill: false, notice: String::new(), options, last: Instant::now() } }
 fn update(&mut self, input: Value) { if self.paused { return }; let data = input.get("payload").filter(|x| x.is_object()).cloned().unwrap_or(input); if data.get("cpu_mhz").is_none() && data.get("heap").is_none() && data.get("uptime_ms").is_none() { return; } self.data = data; let cap = (self.options.history_seconds * self.options.refresh_rate as usize).max(10);
  for (h, value) in [(&mut self.cpu0, num(&self.data, "cpu_core0")), (&mut self.cpu1, num(&self.data, "cpu_core1"))] { h.push_back(value); while h.len() > cap { h.pop_front(); } }; self.last = Instant::now();
  let count = self.data.get("tasks").and_then(Value::as_array).map_or(0, Vec::len); self.selected = self.selected.min(count.saturating_sub(1)); } }
fn section(out: &mut impl Write, title: &str, width: u16, p: Palette) -> Result<()> { queue!(out, SetForegroundColor(p.accent), Print(format!(" +-- {title} {}\n", "-".repeat((width as usize).saturating_sub(title.len() + 6)))))?; Ok(()) }
fn metric(out: &mut impl Write, label: &str, value: f64, suffix: &str, width: usize, p: Palette) -> Result<()> { let color = if value >= 90.0 { p.bad } else if value >= 75.0 { p.warn } else { p.good }; queue!(out, SetForegroundColor(p.muted), Print(format!(" {label:<8}")), SetForegroundColor(color), Print(bar(value, width)), Print(format!(" {:>5.1}% {suffix}\n", value)))?; Ok(()) }
fn draw_cpu(out: &mut impl Write, app: &App, cols: u16, p: Palette) -> Result<()> { section(out, "CPU", cols, p)?; let w = (cols as usize).saturating_sub(30).clamp(8, 36); metric(out, "Core 0", num(&app.data, "cpu_core0"), &format!("{} MHz", uint(&app.data, "cpu_mhz")), w, p)?; metric(out, "Core 1", num(&app.data, "cpu_core1"), "", w, p)?; queue!(out, SetForegroundColor(p.muted), Print(format!("   history [{}]\n", app.cpu0.iter().rev().take(w).rev().map(|x| if *x > 75.0 {'#'} else if *x > 35.0 {'+'} else {'.'}).collect::<String>())))?; Ok(()) }
fn draw_memory(out: &mut impl Write, app: &App, cols: u16, p: Palette) -> Result<()> { section(out, "MEMORY / STORAGE", cols, p)?; let free = uint(&app.data, "heap"); let total = uint(&app.data, "total_heap"); let w = (cols as usize).saturating_sub(47).clamp(8, 30); metric(out, "Heap", heap_pct(&app.data), &format!("{} free / {} total", bytes(free), bytes(total)), w, p)?; let psram = uint(&app.data, "psram"); if psram > 0 { metric(out, "PSRAM", 100.0 * psram.saturating_sub(uint(&app.data, "psram_free")) as f64 / psram as f64, &format!("{} free", bytes(uint(&app.data, "psram_free"))), w, p)?; }; queue!(out, SetForegroundColor(p.muted), Print(format!("   Heap low-water mark: {}   Flash capacity: {}\n", bytes(uint(&app.data, "min_heap")), bytes(uint(&app.data, "flash")))))?; Ok(()) }
fn draw_network(out: &mut impl Write, app: &App, cols: u16, p: Palette) -> Result<()> { section(out, "NETWORK / DEVICE", cols, p)?; let rssi = num(&app.data, "rssi"); metric(out, "WiFi", ((rssi + 100.0) * 2.0).clamp(0.0, 100.0), &format!("{rssi:.0} dBm"), (cols as usize).saturating_sub(34).clamp(8, 34), p)?; queue!(out, SetForegroundColor(p.muted), Print(format!("   TX {} B/s   RX {} B/s   Temperature {:.1} C   Tasks {}\n", uint(&app.data, "tx_rate"), uint(&app.data, "rx_rate"), num(&app.data, "temp_c"), uint(&app.data, "task_count"))))?; Ok(()) }
fn draw_tasks(out: &mut impl Write, app: &App, cols: u16, rows: u16, p: Palette) -> Result<()> { section(out, "FREERTOS TASKS", cols, p)?; queue!(out, SetForegroundColor(p.muted), Print("   PID     NAME                 STATE       CPU    STACK     PRI  OWNER\n"))?; let tasks = app.data.get("tasks").and_then(Value::as_array).map(Vec::as_slice).unwrap_or(&[]); let available = rows.saturating_sub(8) as usize; let start = app.selected.saturating_sub(available / 2);
 for (i, task) in tasks.iter().enumerate().skip(start).take(available) { queue!(out, SetForegroundColor(if i == app.selected { p.accent } else { p.good }), Print(if i == app.selected { ">  " } else { "   " }), Print(format!("{:<7} {:<20} {:<11} {:>4.0}% {:>9} {:>3}  {}\n", uint(task, "pid"), crop(&strv(task, "name", "?"), 20), crop(&strv(task, "state", "?"), 11), num(task, "cpu"), bytes(uint(task, "stack_hwm")), uint(task, "priority"), strv(task, "user", "app"))))?; }
 if tasks.is_empty() { queue!(out, SetForegroundColor(p.muted), Print("   No task metadata in this sample.\n"))?; }; Ok(()) }
fn draw_help(out: &mut impl Write, cols: u16, p: Palette) -> Result<()> { section(out, "KEYBOARD SHORTCUTS", cols, p)?; queue!(out, SetForegroundColor(p.good), Print("   1 / 2 / 3 / 6     CPU, memory, tasks, network views\n   Up / Down          Select a FreeRTOS task\n   k                  Kill the selected non-system task\n   Space              Pause / resume incoming samples\n   h or ?             This help screen\n   q                  Quit\n\n"), SetForegroundColor(p.muted), Print("   Config: ~/.config/es32-top/config.toml\n   [ui] theme = \"nord\"; refresh_rate = 4\n   [monitor] history_seconds = 60\n   Themes: default, nord, dracula, solarized, monokai, high-contrast, minimal\n"))?; Ok(()) }
fn draw(app: &App) -> Result<()> { let mut out = std::io::stdout(); let (cols, rows) = terminal::size()?; let p = palette(&app.options.theme); queue!(out, cursor::MoveTo(0, 0), SetBackgroundColor(p.bg), Clear(ClearType::All), SetForegroundColor(p.accent), Print(format!(" ESP-TOP  {}  ", app.view.title())), SetForegroundColor(p.muted), Print(format!("{} | {} | {} | {}\n", strv(&app.data, "chip", "waiting for device"), uptime(uint(&app.data, "uptime_ms")), if app.paused {"PAUSED"} else {"LIVE"}, app.options.theme)), Print(format!(" {}\n", "=".repeat(cols.saturating_sub(1) as usize))))?;
 if app.view == View::Help { draw_help(&mut out, cols, p)?; } else if app.data.is_null() { queue!(out, SetForegroundColor(p.warn), Print("\n Waiting for newline-delimited ESP32 telemetry...\n\n"), SetForegroundColor(p.muted), Print(" Check the serial port, baud rate, and firmware output.\n"))?; } else { match app.view { View::Dashboard => { draw_cpu(&mut out, app, cols, p)?; draw_memory(&mut out, app, cols, p)?; if rows > 24 { draw_tasks(&mut out, app, cols, rows.saturating_sub(14), p)? } else { draw_network(&mut out, app, cols, p)? } }, View::Cpu => draw_cpu(&mut out, app, cols, p)?, View::Memory => draw_memory(&mut out, app, cols, p)?, View::Tasks => draw_tasks(&mut out, app, cols, rows, p)?, View::Network => draw_network(&mut out, app, cols, p)?, View::Help => {} }; queue!(out, SetForegroundColor(p.muted), Print(format!("\n [1] CPU [2] Memory [3] Tasks [6] Network [k] Kill [h/?] Help [space] Pause [q] Quit  sample {}ms ago", app.last.elapsed().as_millis())))?; if !app.notice.is_empty() { queue!(out, SetForegroundColor(p.warn), Print(format!("\n {}", app.notice)))?; } }; queue!(out, ResetColor)?; out.flush()?; Ok(()) }
pub fn list_ports() -> Result<()> { for port in serialport::available_ports()? { println!("{}\t{:?}", port.port_name, port.port_type); } Ok(()) }
struct Terminal; impl Terminal { fn enter() -> Result<Self> { terminal::enable_raw_mode()?; execute!(std::io::stdout(), EnterAlternateScreen, cursor::Hide)?; Ok(Self) } } impl Drop for Terminal { fn drop(&mut self) { let _ = terminal::disable_raw_mode(); let _ = execute!(std::io::stdout(), cursor::Show, ResetColor, Clear(ClearType::All), LeaveAlternateScreen); } }
fn kill_selected(serial: &mut dyn Write, app: &mut App) -> Result<()> { let Some(task) = app.data.get("tasks").and_then(Value::as_array).and_then(|tasks| tasks.get(app.selected)) else { app.notice = "No task selected.".into(); return Ok(()); }; let name = strv(task, "name", ""); if task.get("protected").and_then(Value::as_bool).unwrap_or(false) || strv(task, "user", "") == "system" { app.notice = format!("{name} is a protected system task."); return Ok(()); }; let pid = uint(task, "pid"); if pid == 0 { app.notice = format!("Cannot kill {name}: it has no task id."); return Ok(()); }; let command = serde_json::json!({"cmd":"kill", "pid":pid, "name":name}).to_string() + "\n"; serial.write_all(command.as_bytes())?; serial.flush()?; app.notice = format!("Kill requested for {name} (pid {pid})."); Ok(()) }
fn run_legacy(port: &str, baud: u32, options: TuiOptions) -> Result<()> { let mut serial = serialport::new(port, baud).timeout(Duration::from_millis(25)).open().with_context(|| format!("cannot open serial port {port}"))?; let _term = Terminal::enter()?; let mut app = App::new(options); let mut buffer = String::new(); let mut dirty = true; let mut last_draw = Instant::now() - Duration::from_millis(100);
 loop { let mut raw = [0; 2048]; match serial.read(&mut raw) { Ok(n) => dirty |= consume(&raw[..n], &mut buffer, &mut app), Err(e) if matches!(e.kind(), std::io::ErrorKind::TimedOut | std::io::ErrorKind::Interrupted) => {}, Err(e) => return Err(e.into()) }; if event::poll(Duration::from_millis(20))? { if let Event::Key(key) = event::read()? { match key.code { KeyCode::Char('q' | 'Q') => break, KeyCode::Char('h' | 'H' | '?') => { app.view = View::Help; dirty = true; }, KeyCode::Char('1') => { app.view = View::Cpu; dirty = true; }, KeyCode::Char('2') => { app.view = View::Memory; dirty = true; }, KeyCode::Char('3') => { app.view = View::Tasks; dirty = true; }, KeyCode::Char('6') => { app.view = View::Network; dirty = true; }, KeyCode::Char('0') | KeyCode::Esc => { app.view = View::Dashboard; dirty = true; }, KeyCode::Char(' ') => { app.paused = !app.paused; dirty = true; }, KeyCode::Char('k' | 'K') => { kill_selected(&mut serial, &mut app)?; dirty = true; }, KeyCode::Up => { app.selected = app.selected.saturating_sub(1); dirty = true; }, KeyCode::Down => { let n = app.data.get("tasks").and_then(Value::as_array).map_or(0, Vec::len); app.selected = (app.selected + 1).min(n.saturating_sub(1)); dirty = true; }, _ => {} } } }; if dirty || last_draw.elapsed() >= Duration::from_millis(100) { draw(&app)?; last_draw = Instant::now(); dirty = false; } }; Ok(()) }
fn consume(raw: &[u8], buffer: &mut String, app: &mut App) -> bool { buffer.push_str(&String::from_utf8_lossy(raw)); if buffer.len() > 65_536 { buffer.clear(); }; let mut changed = false; while let Some(end) = buffer.find('\n') { let line = buffer[..end].trim().to_owned(); buffer.drain(..=end); if let Ok(data) = serde_json::from_str(&line) { let before = app.last; app.update(data); changed |= app.last != before; } } changed }

fn gauge_color(value: f64) -> TColor { if value >= 90.0 { TColor::Red } else if value >= 75.0 { TColor::Yellow } else { TColor::Green } }
fn spark_data(history: &VecDeque<f64>) -> Vec<u64> { history.iter().map(|v| v.clamp(0.0, 100.0) as u64).collect() }
fn panel<'a>(title: &'a str) -> Block<'a> { Block::default().title(Span::styled(format!("─ {title} "), Style::default().fg(TColor::Cyan).add_modifier(Modifier::BOLD))).borders(Borders::ALL).border_type(ratatui::widgets::BorderType::Rounded) }
fn render_header(frame: &mut ratatui::Frame, app: &App, area: Rect, connected: bool) { let status = if connected { "● CONNECTED" } else { "○ DISCONNECTED / RECONNECTING" }; let color = if connected { TColor::Green } else { TColor::Red }; let text = Line::from(vec![Span::styled(" ESP32-TOP ", Style::default().fg(TColor::Cyan).add_modifier(Modifier::BOLD)), Span::raw("│ "), Span::styled(strv(&app.data, "chip", "waiting for device"), Style::default().fg(TColor::White)), Span::raw(" │ uptime "), Span::styled(uptime(uint(&app.data, "uptime_ms")), Style::default().fg(TColor::Yellow)), Span::raw(" │ "), Span::styled(status, Style::default().fg(color))]); frame.render_widget(Paragraph::new(text).block(panel("Device")), area); }
fn render_metrics(frame: &mut ratatui::Frame, app: &App, area: Rect) { let cols = Layout::default().direction(Direction::Horizontal).constraints([Constraint::Percentage(55), Constraint::Percentage(45)]).split(area); let cpu = Layout::default().direction(Direction::Vertical).constraints([Constraint::Length(3), Constraint::Min(3)]).split(cols[0]); let c0 = num(&app.data, "cpu_core0"); frame.render_widget(Gauge::default().block(panel("CPU Core 0")).gauge_style(Style::default().fg(gauge_color(c0))).percent(c0.clamp(0.0, 100.0) as u16).label(format!("{c0:>5.1}%  {} MHz", uint(&app.data, "cpu_mhz"))), cpu[0]); frame.render_widget(Sparkline::default().block(panel("CPU history")).data(&spark_data(&app.cpu0)).max(100).style(Style::default().fg(gauge_color(c0))).bar_set(symbols::bar::THREE_LEVELS), cpu[1]); let mem = Layout::default().direction(Direction::Vertical).constraints([Constraint::Length(3), Constraint::Length(3), Constraint::Min(3)]).split(cols[1]); let hp = heap_pct(&app.data); frame.render_widget(Gauge::default().block(panel("Heap pressure")).gauge_style(Style::default().fg(gauge_color(hp))).percent(hp as u16).label(format!("{hp:>5.1}% used  {} / {}", bytes(uint(&app.data, "heap")), bytes(uint(&app.data, "total_heap")))), mem[0]); let ps = uint(&app.data, "psram"); let pp = if ps == 0 { 0.0 } else { 100.0 * ps.saturating_sub(uint(&app.data, "psram_free")) as f64 / ps as f64 }; frame.render_widget(Gauge::default().block(panel("PSRAM pressure")).gauge_style(Style::default().fg(gauge_color(pp))).percent(pp as u16).label(format!("{pp:>5.1}% used")), mem[1]); frame.render_widget(Paragraph::new(vec![Line::from(format!("Wi-Fi {:>4.0} dBm   temp {:.1} C", num(&app.data, "rssi"), num(&app.data, "temp_c"))), Line::from(format!("Tasks {:>4}       flash {}", uint(&app.data, "task_count"), bytes(uint(&app.data, "flash"))))]).block(panel("Network / device")), mem[2]); }
fn render_tasks(frame: &mut ratatui::Frame, app: &App, area: Rect) { let tasks = app.data.get("tasks").and_then(Value::as_array).cloned().unwrap_or_default(); let header = Row::new(["PID", "TASK", "CORE", "STATE", "CPU", "STACK", "PRI", "OWNER"]).style(Style::default().fg(TColor::Cyan).add_modifier(Modifier::BOLD)); let rows = tasks.iter().map(|t| Row::new([uint(t, "pid").to_string(), crop(&strv(t, "name", "?"), 18), strv(t, "core", "-"), crop(&strv(t, "state", "?"), 11), format!("{:>4.0}%", num(t, "cpu")), bytes(uint(t, "stack_hwm")), uint(t, "priority").to_string(), strv(t, "user", "app")])); let table = Table::new(rows, [Constraint::Length(7), Constraint::Min(18), Constraint::Length(5), Constraint::Length(12), Constraint::Length(6), Constraint::Length(10), Constraint::Length(5), Constraint::Length(8)]).header(header).block(panel("Tasks")).row_highlight_style(Style::default().bg(TColor::Blue).fg(TColor::White).add_modifier(Modifier::BOLD)).highlight_symbol("▶ "); let mut state = TableState::default().with_selected((!tasks.is_empty()).then_some(app.selected)); frame.render_stateful_widget(table, area, &mut state); }
fn render_footer(frame: &mut ratatui::Frame, app: &App, area: Rect) { let text: String = if app.confirm_kill { " CONFIRM KILL? y yes  n/Esc cancel ".into() } else if !app.notice.is_empty() { format!(" {}  │  ↑↓ select  k kill  q quit ", app.notice) } else { " ↑↓ select  k kill  1 CPU  2 memory  3 tasks  q quit ".into() }; frame.render_widget(Paragraph::new(text).style(Style::default().fg(TColor::DarkGray)), area); }
fn draw_ratatui(term: &mut UiTerminal<CrosstermBackend<std::io::Stdout>>, app: &App, connected: bool) -> Result<()> { term.draw(|frame| { let chunks = Layout::default().direction(Direction::Vertical).constraints([Constraint::Length(3), Constraint::Length(8), Constraint::Min(6), Constraint::Length(1)]).split(frame.area()); render_header(frame, app, chunks[0], connected); render_metrics(frame, app, chunks[1]); render_tasks(frame, app, chunks[2]); render_footer(frame, app, chunks[3]); })?; Ok(()) }
pub fn run(port: &str, baud: u32, options: TuiOptions) -> Result<()> { let mut serial = serialport::new(port, baud).timeout(Duration::from_millis(25)).open().with_context(|| format!("cannot open serial port {port}"))?; let _term = Terminal::enter()?; let backend = CrosstermBackend::new(std::io::stdout()); let mut term = UiTerminal::new(backend)?; let mut app = App::new(options); let mut buffer = String::new(); let mut last_sample = Instant::now(); let mut dirty = true; loop { let mut raw = [0; 2048]; match serial.read(&mut raw) { Ok(n) => { if consume(&raw[..n], &mut buffer, &mut app) { last_sample = Instant::now(); dirty = true; } }, Err(e) if matches!(e.kind(), std::io::ErrorKind::TimedOut | std::io::ErrorKind::Interrupted) => {}, Err(_) => {} }; if event::poll(Duration::from_millis(20))? { if let Event::Key(key) = event::read()? { match key.code { KeyCode::Char('q' | 'Q') => break, KeyCode::Up => { app.selected = app.selected.saturating_sub(1); dirty = true; }, KeyCode::Down => { let n = app.data.get("tasks").and_then(Value::as_array).map_or(0, Vec::len); app.selected = (app.selected + 1).min(n.saturating_sub(1)); dirty = true; }, KeyCode::Char('k' | 'K') if !app.confirm_kill => { app.confirm_kill = true; dirty = true; }, KeyCode::Char('y' | 'Y') if app.confirm_kill => { app.confirm_kill = false; kill_selected(&mut serial, &mut app)?; dirty = true; }, KeyCode::Char('n' | 'N') | KeyCode::Esc if app.confirm_kill => { app.confirm_kill = false; dirty = true; }, KeyCode::Char(' ') => { app.paused = !app.paused; dirty = true; }, _ => {} } } }; let connected = last_sample.elapsed() < Duration::from_secs(3); if dirty || last_sample.elapsed() < Duration::from_millis(250) { draw_ratatui(&mut term, &app, connected)?; dirty = false; } }; Ok(()) }
#[cfg(test)] mod tests { use super::*; #[test] fn formatting() { assert_eq!(bytes(1536), "1.5 KiB"); assert_eq!(uptime(3_661_000), "01:01:01"); } #[test] fn bounded() { let mut app = App::new(TuiOptions { history_seconds: 1, refresh_rate: 1, ..Default::default() }); for _ in 0..20 { app.update(serde_json::json!({"uptime_ms": 1, "cpu_core0": 20, "cpu_core1": 40})); }; assert!(app.cpu0.len() <= 10); } #[test] fn ignores_non_telemetry_envelope() { let mut app = App::new(TuiOptions::default()); app.update(serde_json::json!({"protocol":"1.0", "type":"WORKLOAD_LIST", "payload":{"workloads":[]}})); assert!(app.data.is_null()); } #[test] fn kill_selected_writes_a_command() { let mut app = App::new(TuiOptions::default()); app.update(serde_json::json!({"uptime_ms": 1, "tasks":[{"pid":42,"name":"worker","protected":false}]})); let mut output = Vec::new(); kill_selected(&mut output, &mut app).unwrap(); assert_eq!(String::from_utf8(output).unwrap(), "{\"cmd\":\"kill\",\"name\":\"worker\",\"pid\":42}\n"); } }
