use anyhow::{Context, Result};
use crossterm::{cursor, event::{self, Event, KeyCode}, execute, terminal::{self, Clear, ClearType}};
use serde_json::Value;
use std::io::{Read, Write};
use std::time::Duration;

fn field(data: &Value, name: &str) -> String { data.get(name).map(|value| value.to_string()).unwrap_or_else(|| "0".into()) }
fn render(data: &Value) -> Result<()> { let mut stdout = std::io::stdout(); execute!(stdout, cursor::MoveTo(0, 0), Clear(ClearType::All))?; println!("ESP-TOP  Rust host / C++ runtime                              [q] quit"); println!("────────────────────────────────────────────────────────────────────────"); println!("CPU     {} MHz  core0 {}%  core1 {}%", field(data,"cpu_mhz"), field(data,"cpu_core0"), field(data,"cpu_core1")); println!("RAM     free {} B  total {} B  min {} B", field(data,"heap"), field(data,"total_heap"), field(data,"min_heap")); println!("NETWORK RSSI {} dBm", field(data,"rssi")); println!("FLASH   {} B  PSRAM {} B", field(data,"flash"), field(data,"psram")); println!("UPTIME  {} ms\n\nTASKS\nPID    NAME                 STATE       STACK", field(data,"uptime")); if let Some(tasks) = data.get("tasks").and_then(Value::as_array) { for task in tasks { println!("{:<6} {:<20} {:<11} {} B", task.get("pid").and_then(Value::as_i64).unwrap_or(0), task.get("name").and_then(Value::as_str).unwrap_or("?"), task.get("state").and_then(Value::as_str).unwrap_or("?"), task.get("stack_hwm").and_then(Value::as_i64).unwrap_or(0)); } } std::io::stdout().flush()?; Ok(()) }
pub fn list_ports() -> Result<()> { let ports = serialport::available_ports()?; for port in ports { println!("{}\t{:?}", port.port_name, port.port_type); } Ok(()) }
pub fn run(port: &str, baud: u32) -> Result<()> { let mut serial = serialport::new(port, baud).timeout(Duration::from_millis(100)).open().with_context(|| format!("cannot open serial port {port}"))?; terminal::enable_raw_mode()?; let mut buffer = String::new(); let result = loop { let mut bytes = [0u8; 1024]; match serial.read(&mut bytes) { Ok(count) => { buffer_lines(&bytes[..count], &mut buffer)?; } Err(error) if error.kind() == std::io::ErrorKind::TimedOut || error.kind() == std::io::ErrorKind::Interrupted => {} Err(error) => break Err(error.into()) }; match event::poll(Duration::from_millis(20)) { Ok(true) => match event::read() { Ok(Event::Key(key)) if matches!(key.code, KeyCode::Char('q') | KeyCode::Char('Q')) => break Ok(()), Ok(_) => {}, Err(error) if error.kind() == std::io::ErrorKind::Interrupted => break Ok(()), Err(error) => break Err(error.into()) }, Ok(false) => {}, Err(error) if error.kind() == std::io::ErrorKind::Interrupted => break Ok(()), Err(error) => break Err(error.into()) } }; terminal::disable_raw_mode()?; println!(); result }
fn buffer_lines(bytes: &[u8], buffer: &mut String) -> Result<()> { buffer.push_str(&String::from_utf8_lossy(bytes)); while let Some(index) = buffer.find('\n') { let line = buffer[..index].trim().to_string(); buffer.drain(..=index); if let Ok(data) = serde_json::from_str::<Value>(&line) { render(&data)?; } } Ok(()) }
